import os
from pathlib import Path
from setuptools import setup
from sys import platform


req_list = ['numpy', 'qkeras', 'hls4ml']

if platform == 'darwin':
    req_list.append('tensorflow-macos==2.8.0')
else:
    req_list.append('tensorflow==2.8.0')

cur_dir = os.getcwd()
os.chdir(Path(__file__).parent / 'hlsestimatorml' / 'hls4ml')
package_data_hls4ml = list(map(str, Path('single_models').rglob('*.*')))
os.chdir(cur_dir)

setup(
    name='hls-estimator-ml',
    author='Maksymilian Graczyk',
    version='0.1',
    description='Fast estimation of the hardware implementation '
    'of neural networks generated by HLS-based ML frameworks',
    packages=['hlsestimatorml', 'hlsestimatorml.hls4ml'],
    package_data={'hlsestimatorml.hls4ml': package_data_hls4ml},
    install_requires=req_list
)
