from setuptools import setup
from sys import platform


req_list = ['numpy', 'qkeras', 'hls4ml']

if platform == 'darwin':
    req_list.append('tensorflow-macos==2.8.0')
else:
    req_list.append('tensorflow==2.8.0')

setup(
    name='hls-estimator-ml',
    author='Maksymilian Graczyk',
    version='0.1',
    description='Fast estimation of the hardware implementation '
    'of neural networks generated by HLS-based ML frameworks',
    packages=['hlsestimatorml'],
    package_requires=req_list
)
